### ISSUE TITLE
[BUG] Variável de eventNoInteraction da documentação não bate com o valor configurado no gtmCleanup.

### ISSUE THREAD

**Issue by jubelcassio** [DP6/easy-collect#25]
**Describe the bug**
Na documentação de implementação do easy-collect o valor para ser utilizado na variável de camada de dados está como "eventNoInteraction", enquanto na função de cleanup este valor está como "noInteraction".

**Expected behavior**
O ajuste é bem simples, seria apenas atualizar a documentação  ou mudar o campo do cleanup.

**Screenshots**
![image](https://user-images.githubusercontent.com/12815292/116904518-2e3cec00-ac14-11eb-9f50-69d57ded9a52.png)
![image](https://user-images.githubusercontent.com/12815292/116904532-339a3680-ac14-11eb-93b7-2ffbacc18d34.png)

**Comment by carolmsl** [comment]
@jubelcassio ajuste realizado :)
