### ISSUE TITLE
Adicionar sumário ou Table of contents na documentação técnica

### ISSUE THREAD

**Issue by GuilhermeFaga** [DP6/easy-collect#43]
**Is your feature request related to a problem? Please describe.**
Sim, complicado achar algo rapidamente na documentação.

**Describe the solution you'd like**
Adicionar um sumário na documentação técnica.

**Describe alternatives you've considered**
Nenhuma.

**Additional context**
Nada.

**Comment by carolmsl** [comment]
Feito!
